### ISSUE TITLE
Missing project name validation

### ISSUE THREAD

**Issue by tokuhirom** [JakubNeukirch/kvision-project-wizard#16]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/21084/168006383-389df2df-a1ca-4004-86ae-108c70488dd2.png">

if artifactId contains a character, that doesn't valid for package name, it cause the compilation error.

**Comment by FleetAdmiralJakob** [comment]
@JakubNeukirch Pls. fix it

**Comment by rjaros** [comment]
Fixed in 0.6.0.
